version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"